// Generated by scripts/build-snake-data.mjs — do not edit by hand.
// Re-run the script to regenerate after updating raw iNat data or curation.

import type { SnakeCandidate } from "@/lib/types";

export const snakeCandidates: SnakeCandidate[] = [
  {
    "id": "chrysopelea-ornata",
    "sci": "Chrysopelea ornata",
    "en": "Golden Tree Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Chrysopelea",
    "inatId": 27207,
    "observationsThailand": 1741,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Chrysopelea_ornata",
    "wikipediaSummary": "Chrysopelea ornata is a colubrid snake found in both South and Southeast Asia. It is, along with the other species in its genus Chrysopelea, very unusual in that it is capable of a type of gliding flight. It is also rear-fanged. Currently, three subspecies are recognized. The snake's striking looks and capability of gliding make it a popular choice for captivity.",
    "photo": {
      "url": "/snakes/27207.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) chintan sheth, some rights reserved (CC BY-NC), uploaded by chintan sheth",
      "source": "https://www.inaturalist.org/photos/163576071"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-macrops",
    "sci": "Trimeresurus macrops",
    "en": "Kramer's Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 146510,
    "observationsThailand": 1173,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_macrops",
    "wikipediaSummary": "Trimeresurus macrops is a venomous pit viper species endemic to Southeast Asia. No subspecies are currently recognized. Common names include large-eyed pitviper and green pit viper.",
    "photo": {
      "url": "/snakes/146510.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Sam Hambly, some rights reserved (CC BY-NC), uploaded by Sam Hambly",
      "source": "https://www.inaturalist.org/photos/310877300"
    },
    "draft": true
  },
  {
    "id": "ahaetulla-prasina",
    "sci": "Ahaetulla prasina",
    "en": "Oriental Whipsnake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ahaetulla",
    "inatId": 30187,
    "observationsThailand": 959,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ahaetulla_prasina",
    "wikipediaSummary": "Ahaetulla prasina is a species of snake in the family Colubridae native to southern Asia. Its common names include Asian vine snake, Boie's whip snake, Gunther's whip snake, and Oriental whip snake.",
    "photo": {
      "url": "/snakes/30187.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) aswad andriyanto, some rights reserved (CC BY-NC), uploaded by aswad andriyanto",
      "source": "https://www.inaturalist.org/photos/24080870"
    },
    "draft": true
  },
  {
    "id": "malayopython-reticulatus",
    "sci": "Malayopython reticulatus",
    "en": "Reticulated Python",
    "th": null,
    "family": "Pythonidae",
    "genus": "Malayopython",
    "inatId": 491869,
    "observationsThailand": 871,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/reticulated_python",
    "wikipediaSummary": "The reticulated python (Python reticulatus) is a species of python found in Southeast Asia. They are the world's longest snakes and longest reptiles, and among the three heaviest snakes. Like all pythons, they are nonvenomous constrictors and normally not considered dangerous to humans. However, cases of people killed (and in at least one case eaten) by reticulated pythons have been documented.",
    "photo": {
      "url": "/snakes/491869.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Jeff LeClere, some rights reserved (CC BY-NC), uploaded by Jeff LeClere",
      "source": "https://www.inaturalist.org/photos/89211391"
    },
    "draft": true
  },
  {
    "id": "oligodon-fasciolatus",
    "sci": "Oligodon fasciolatus",
    "en": "Small-banded Kukri Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Oligodon",
    "inatId": 29263,
    "observationsThailand": 743,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Oligodon_fasciolatus",
    "wikipediaSummary": "Oligodon fasciolatus, commonly known as the small-banded kukri snake or the fasciolated kukri snake, is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/29263.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Sam Hambly, some rights reserved (CC BY-NC), uploaded by Sam Hambly",
      "source": "https://www.inaturalist.org/photos/308339213"
    },
    "draft": true
  },
  {
    "id": "ptyas-korros",
    "sci": "Ptyas korros",
    "en": "Indo-Chinese Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ptyas",
    "inatId": 28870,
    "observationsThailand": 643,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ptyas_korros",
    "wikipediaSummary": "Ptyas korros, commonly known as the Chinese ratsnake or Indo-Chinese rat snake, is a species of colubrid snake endemic to Southeast Asia.",
    "photo": {
      "url": "/snakes/28870.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) sandcarve, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/389336756"
    },
    "draft": true
  },
  {
    "id": "fowlea-flavipunctata",
    "sci": "Fowlea flavipunctata",
    "en": "Yellow-spotted Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Fowlea",
    "inatId": 966797,
    "observationsThailand": 547,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Yellow-spotted_keelback",
    "wikipediaSummary": "The yellow-spotted keelback (Fowlea flavipunctatus) is a species of colubrid snake found in India, Thailand, China, West Malaysia, Laos, Cambodia, Vietnam, Indonesia (Sumatra, Java, and Kalimantan) Its type locality is: Island of Hong Kong (Hong Kong) and Canton River?, China",
    "photo": {
      "url": "/snakes/966797.jpeg",
      "license": "cc-by-nc-nd",
      "attribution": "(c) Bug's eyes photography, some rights reserved (CC BY-NC-ND), uploaded by Bug's eyes photography",
      "source": "https://www.inaturalist.org/photos/108115341"
    },
    "draft": true
  },
  {
    "id": "white-lipped-pit-viper",
    "sci": "Trimeresurus albolabris",
    "en": "White-lipped Pit Viper",
    "th": "งูเขียวหางไหม้",
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 146506,
    "observationsThailand": 489,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_albolabris",
    "wikipediaSummary": "Trimeresurus albolabris, the white-lipped pit viper, is a venomous pit viper species endemic to Southeast Asia. Three subspecies are currently recognized, including the nominate subspecies described here.",
    "photo": {
      "url": "/snakes/146506.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Leonid A. Neymark, some rights reserved (CC BY-NC), uploaded by Leonid A. Neymark",
      "source": "https://www.inaturalist.org/photos/48975775"
    },
    "draft": false,
    "danger": 4,
    "venom": "Hemotoxic",
    "size": "60–100 cm",
    "swatch": [
      "#4F9F4A",
      "#F1E9A6",
      "#9C3A1C"
    ],
    "idCues": [
      "Bright leaf-green body",
      "White/yellow lower lip",
      "Rust-coloured tail tip"
    ],
    "habitat": "Trees, gardens, wood piles — common in Bangkok",
    "handle": "Most common venomous bite in BKK. Use a long stick. Call rescue.",
    "firstAid": "Call 1669. Keep still. Hospital monitoring. Antivenom available."
  },
  {
    "id": "xenopeltis-unicolor",
    "sci": "Xenopeltis unicolor",
    "en": "Asian Sunbeam Snake",
    "th": null,
    "family": "Xenopeltidae",
    "genus": "Xenopeltis",
    "inatId": 32407,
    "observationsThailand": 477,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Xenopeltis_unicolor",
    "wikipediaSummary": "Xenopeltis unicolor is a non-venomous sunbeam snake species found in Southeast Asia and some regions of Indonesia. This is a primitive snake known for both its highly iridescent scales and its ability to reproduce quickly, as it is oviparous and as such can lay up to 10 eggs at a time. No subspecies are currently recognized.",
    "photo": {
      "url": "/snakes/32407.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/118977944"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-lanna",
    "sci": "Trimeresurus lanna",
    "en": "Lanna Green Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 1592009,
    "observationsThailand": 451,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1592009.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/118421024"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-pictus",
    "sci": "Dendrelaphis pictus",
    "en": "Painted Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 26644,
    "observationsThailand": 423,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_pictus",
    "wikipediaSummary": "Dendrelaphis pictus (painted bronzeback) is a species of snake found in Southeast Asia and India.",
    "photo": {
      "url": "/snakes/26644.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) budak, some rights reserved (CC BY-NC), uploaded by budak",
      "source": "https://www.inaturalist.org/photos/4837586"
    },
    "draft": true
  },
  {
    "id": "malayan-pit-viper",
    "sci": "Calloselasma rhodostoma",
    "en": "Malayan Pit Viper",
    "th": "งูกะปะ",
    "family": "Viperidae",
    "genus": "Calloselasma",
    "inatId": 30825,
    "observationsThailand": 410,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Calloselasma_rhodostoma",
    "wikipediaSummary": "Calloselasma is a monotypic genus created for a venomous pit viper species, C. rhodostoma, which is endemic to Southeast Asia from Thailand to northern Malaysia and on the island of Java. No subspecies are currently recognized.",
    "photo": {
      "url": "/snakes/30825.jpg",
      "license": "cc-by",
      "attribution": "(c) Gerard Chartier, some rights reserved (CC BY)",
      "source": "https://www.inaturalist.org/photos/54423754"
    },
    "draft": false,
    "danger": 5,
    "venom": "Hemotoxic",
    "size": "60–100 cm",
    "swatch": [
      "#B9907A",
      "#6E3A28",
      "#3A1C12"
    ],
    "idCues": [
      "Distinctly triangular head, much wider than neck",
      "Pinkish-brown with dark zigzag triangles",
      "Heat pit between eye and nostril"
    ],
    "habitat": "Rubber plantations, leaf litter, gardens",
    "handle": "Does not flee — sits motionless. Step around carefully.",
    "firstAid": "Call 1669. Keep limb still below heart. Bleeding for days — hospital now."
  },
  {
    "id": "coelognathus-radiatus",
    "sci": "Coelognathus radiatus",
    "en": "Copperhead Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Coelognathus",
    "inatId": 30235,
    "observationsThailand": 378,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Coelognathus_radiatus",
    "wikipediaSummary": "The radiated ratsnake, copperhead rat snake or copper-headed trinket snake (Coelognathus radiatus) is a nonvenomous species of colubrid snake.",
    "photo": {
      "url": "/snakes/30235.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) John Howes, some rights reserved (CC BY-NC), uploaded by John Howes",
      "source": "https://www.inaturalist.org/photos/341460857"
    },
    "draft": true
  },
  {
    "id": "ahaetulla-fusca",
    "sci": "Ahaetulla fusca",
    "en": "Indochinese Long-nosed Whipsnake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ahaetulla",
    "inatId": 1439532,
    "observationsThailand": 372,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ahaetulla_fusca",
    "wikipediaSummary": "Ahaetulla fusca, the dark whipsnake, is a species of snake in the family Colubridae. The species is found in Thailand, Cambodia, Vietnam, and Myanmar.",
    "photo": {
      "url": "/snakes/1439532.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/175010951"
    },
    "draft": true
  },
  {
    "id": "tropidolaemus-wagleri",
    "sci": "Tropidolaemus wagleri",
    "en": "Wagler's Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Tropidolaemus",
    "inatId": 30936,
    "observationsThailand": 363,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tropidolaemus_wagleri",
    "wikipediaSummary": "Tropidolaemus wagleri is a venomous pitviper species native to South-East Asia. No subspecies are currently recognized. It is sometimes referred to as the temple viper because of its abundance around the Temple of the Azure Cloud in Malaysia.",
    "photo": {
      "url": "/snakes/30936.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Cheongweei Gan, some rights reserved (CC BY-NC), uploaded by Cheongweei Gan",
      "source": "https://www.inaturalist.org/photos/13230789"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-vogeli",
    "sci": "Trimeresurus vogeli",
    "en": "Vogel’s Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30947,
    "observationsThailand": 363,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_vogeli",
    "wikipediaSummary": "Trimeresurus vogeli is a venomous pitviper species native to Southeast Asia.",
    "photo": null,
    "draft": true
  },
  {
    "id": "rhabdophis-siamensis",
    "sci": "Rhabdophis siamensis",
    "en": "Siamese Red-necked Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Rhabdophis",
    "inatId": 1337910,
    "observationsThailand": 350,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rhabdophis_siamensis",
    "wikipediaSummary": "Rhabdophis siamensis is a keelback snake in the family Colubridae found in Thailand, Vietnam and China.",
    "photo": {
      "url": "/snakes/1337910.jpg",
      "license": "cc-by",
      "attribution": "(c) Noah Kirkland, some rights reserved (CC BY), uploaded by Noah Kirkland",
      "source": "https://www.inaturalist.org/photos/447503916"
    },
    "draft": true
  },
  {
    "id": "monocled-cobra",
    "sci": "Naja kaouthia",
    "en": "Monocled Cobra",
    "th": "งูเห่าหม้อ",
    "family": "Elapidae",
    "genus": "Naja",
    "inatId": 106447,
    "observationsThailand": 347,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Naja_kaouthia",
    "wikipediaSummary": "The monocled cobra (Naja kaouthia), also called monocellate cobra, is a cobra species widespread across South and Southeast Asia and listed as Least Concern by IUCN.",
    "photo": {
      "url": "/snakes/106447.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) herpingvietnam, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/59656179"
    },
    "draft": false,
    "danger": 5,
    "venom": "Neurotoxic + cytotoxic",
    "size": "130–210 cm",
    "swatch": [
      "#5C4A2A",
      "#2E2517",
      "#D7C28A"
    ],
    "idCues": [
      "Wide oval hood",
      "Single O-shaped “monocle” on hood",
      "Dark stripe under eye"
    ],
    "habitat": "Rice paddies, farms, urban edges",
    "handle": "Keep 3+ meters away. Do not corner. Call rescue.",
    "firstAid": "Call 1669. Pressure bandage. Hospital fast."
  },
  {
    "id": "boiga-melanota",
    "sci": "Boiga melanota",
    "en": "Western Mangrove Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 1286556,
    "observationsThailand": 345,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_melanota",
    "wikipediaSummary": "Boiga melanota, the western mangrove cat snake is a species of the mangrove snake, one of the biggest cat snake species in Asia. It is shiny bluish black in colour, marked with 40-50 yellow stripes. The mouth and throat area are yellow, whereas the ventral part of the body is yellowish black. The eyes are greyish in colour. It is categorised as a mildly venomous snake.",
    "photo": {
      "url": "/snakes/1286556.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Tommy, some rights reserved (CC BY-NC), uploaded by Tommy",
      "source": "https://www.inaturalist.org/photos/5677717"
    },
    "draft": true
  },
  {
    "id": "lycodon-capucinus",
    "sci": "Lycodon capucinus",
    "en": "Common Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 104885,
    "observationsThailand": 341,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_capucinus",
    "wikipediaSummary": "Lycodon capucinus, also known as the common wolf snake, is a species of colubrid snake, which is commonly found in the Indo-Australian Archipelago. Named after their enlarged front teeth, which gives them a muzzled appearance similar to canines, it also makes the snout somewhat more squarish than other snakes.",
    "photo": {
      "url": "/snakes/104885.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) hokoonwong, some rights reserved (CC BY-NC), uploaded by hokoonwong",
      "source": "https://www.inaturalist.org/photos/12254663"
    },
    "draft": true
  },
  {
    "id": "psammodynastes-pulverulentus",
    "sci": "Psammodynastes pulverulentus",
    "en": "Common Mock Viper",
    "th": null,
    "family": "Psammodynastidae",
    "genus": "Psammodynastes",
    "inatId": 28999,
    "observationsThailand": 288,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Psammodynastes_pulverulentus",
    "wikipediaSummary": "Psammodynastes pulverulentus, the common mock viper, is a species of snake native to Asia. It is one of the few snake species to possess three hemipenes.",
    "photo": {
      "url": "/snakes/28999.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) chintan sheth, some rights reserved (CC BY-NC), uploaded by chintan sheth",
      "source": "https://www.inaturalist.org/photos/161663251"
    },
    "draft": true
  },
  {
    "id": "cerberus-schneiderii",
    "sci": "Cerberus schneiderii",
    "en": "Southeast Asian Bockadam",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Cerberus",
    "inatId": 200191,
    "observationsThailand": 264,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/200191.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Ajak King, some rights reserved (CC BY-NC), uploaded by Ajak King",
      "source": "https://www.inaturalist.org/photos/209242091"
    },
    "draft": true
  },
  {
    "id": "cylindrophis-jodiae",
    "sci": "Cylindrophis jodiae",
    "en": "Jodi's pipe snake",
    "th": null,
    "family": "Cylindrophiidae",
    "genus": "Cylindrophis",
    "inatId": 539533,
    "observationsThailand": 262,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Cylindrophis_jodiae",
    "wikipediaSummary": "Cylindrophis jodiae, Jodi’s pipe snake, is a species of snake of the family Cylindrophiidae.",
    "photo": {
      "url": "/snakes/539533.jpg",
      "license": "cc-by-sa",
      "attribution": "(c) Rushen, some rights reserved (CC BY-SA)",
      "source": "https://www.inaturalist.org/photos/39013076"
    },
    "draft": true
  },
  {
    "id": "hypsiscopus-murphyi",
    "sci": "Hypsiscopus murphyi",
    "en": "Murphy's Mud Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Hypsiscopus",
    "inatId": 1439424,
    "observationsThailand": 248,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Hypsiscopus_murphyi",
    "wikipediaSummary": "Hypsiscopus murphyi, commonly known as Murphy's mud snake, is species of snake in the family Homalopsidae. It's specific epithet is named after the herpetologist John C. Murphy.",
    "photo": {
      "url": "/snakes/1439424.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Liu Rui Wei, some rights reserved (CC BY-NC), uploaded by Liu Rui Wei",
      "source": "https://www.inaturalist.org/photos/251820149"
    },
    "draft": true
  },
  {
    "id": "ptyas-mucosa",
    "sci": "Ptyas mucosa",
    "en": "Oriental Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ptyas",
    "inatId": 28868,
    "observationsThailand": 241,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ptyas_mucosa",
    "wikipediaSummary": "Ptyas mucosa, commonly known as the oriental ratsnake, Indian rat snake, 'darash' or dhaman, is a common species of colubrid snake found in parts of South and Southeast Asia. Dhamans are large snakes, growing to 2 m (6.6 ft) and occasionally even to 3 m (9.8 ft). Their colour varies from pale browns in dry regions to nearly black in moist forest areas. Dhamans are diurnal, semi-arboreal, non-venom",
    "photo": {
      "url": "/snakes/28868.jpg",
      "license": "cc-by-sa",
      "attribution": "(c) \nArun Kumar Thyadi, some rights reserved (CC BY-SA)",
      "source": "https://www.inaturalist.org/photos/323553661"
    },
    "draft": true
  },
  {
    "id": "homalopsis-mereljcoxi",
    "sci": "Homalopsis mereljcoxi",
    "en": "Jack's Water Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Homalopsis",
    "inatId": 429516,
    "observationsThailand": 212,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/429516.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Thomas Calame, some rights reserved (CC BY-NC), uploaded by Thomas Calame",
      "source": "https://www.inaturalist.org/photos/140847"
    },
    "draft": true
  },
  {
    "id": "malayan-krait",
    "sci": "Bungarus candidus",
    "en": "Malayan Krait",
    "th": "งูสามเหลี่ยมหางแดง",
    "family": "Elapidae",
    "genus": "Bungarus",
    "inatId": 96225,
    "observationsThailand": 207,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Bungarus_candidus",
    "wikipediaSummary": "Bungarus candidus, commonly known as the Malayan krait or blue krait, is a species of krait, a venomous elapid snake.",
    "photo": {
      "url": "/snakes/96225.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Robinp24, some rights reserved (CC BY-NC), uploaded by Robinp24",
      "source": "https://www.inaturalist.org/photos/651253419"
    },
    "draft": false,
    "danger": 5,
    "venom": "Highly neurotoxic",
    "size": "90–160 cm",
    "swatch": [
      "#0E0E0E",
      "#F4F1EA",
      "#0E0E0E"
    ],
    "idCues": [
      "Bold black & white bands, equal width",
      "Triangular cross-section, ridged spine",
      "Glossy scales"
    ],
    "habitat": "Lowland forests, rice fields, often enters homes at night",
    "handle": "Often bites sleepers. Sweep beds. Do not touch.",
    "firstAid": "EMERGENCY. Pressure immobilization. Hospital fast — paralysis develops hours later."
  },
  {
    "id": "boiga-cyanea",
    "sci": "Boiga cyanea",
    "en": "Green Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 27697,
    "observationsThailand": 205,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_cyanea",
    "wikipediaSummary": "Boiga cyanea is a Colubrid snake species found in South Asia, China and South-east Asia.",
    "photo": null,
    "draft": true
  },
  {
    "id": "red-tailed-racer",
    "sci": "Gonyosoma oxycephalum",
    "en": "Red-tailed Green Ratsnake",
    "th": "งูเขียวหางแดง",
    "family": "Colubridae",
    "genus": "Gonyosoma",
    "inatId": 29992,
    "observationsThailand": 201,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Gonyosoma_oxycephalum",
    "wikipediaSummary": "The red-tailed green ratsnake (Gonyosoma oxycephalum, also known as arboreal ratsnake and red-tailed racer) is a species of snake found in Southeast Asia.",
    "photo": {
      "url": "/snakes/29992.jpg",
      "license": "cc-by",
      "attribution": "(c) Lawrence Hylton, some rights reserved (CC BY), uploaded by Lawrence Hylton",
      "source": "https://www.inaturalist.org/photos/472815371"
    },
    "draft": false,
    "danger": 1,
    "venom": "None",
    "size": "180–240 cm",
    "swatch": [
      "#4DAE54",
      "#234A2A",
      "#8B3A24"
    ],
    "idCues": [
      "Vivid bright leaf-green",
      "Reddish-brown tail",
      "Blue-black tongue, black line through eye"
    ],
    "habitat": "Forests, mangroves, high trees",
    "handle": "Non-venomous but bites if cornered. Gently lift with hook.",
    "firstAid": "Wash bite with soap. Tetanus check."
  },
  {
    "id": "lycodon-laoensis",
    "sci": "Lycodon laoensis",
    "en": "Laotian Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 29565,
    "observationsThailand": 195,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_laoensis",
    "wikipediaSummary": "Lycodon laoensis, commonly known as the Laotian wolf snake, is a species of colubrid snake, which is endemic to Asia.",
    "photo": {
      "url": "/snakes/29565.jpg",
      "license": "cc-by-sa",
      "attribution": "(c) Rushen, some rights reserved (CC BY-SA)",
      "source": "https://www.inaturalist.org/photos/22128514"
    },
    "draft": true
  },
  {
    "id": "naja-siamensis",
    "sci": "Naja siamensis",
    "en": "Indochinese Spitting Cobra",
    "th": null,
    "family": "Elapidae",
    "genus": "Naja",
    "inatId": 106450,
    "observationsThailand": 192,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Naja_siamensis",
    "wikipediaSummary": "The Indochinese spitting cobra (Naja siamensis) also called the Thai spitting cobra, Siamese spitting cobra or black-and-white spitting cobra, is a species of spitting cobra found in Southeast Asia.",
    "photo": {
      "url": "/snakes/106450.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) tristanv, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/21257971"
    },
    "draft": true
  },
  {
    "id": "oligodon-taeniatus",
    "sci": "Oligodon taeniatus",
    "en": "Striped Kukri Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Oligodon",
    "inatId": 29224,
    "observationsThailand": 183,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Oligodon_taeniatus",
    "wikipediaSummary": "The striped kukri snake (Oligodon taeniatus) is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/29224.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) tristanv, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/21212605"
    },
    "draft": true
  },
  {
    "id": "python-bivittatus",
    "sci": "Python bivittatus",
    "en": "Burmese Python",
    "th": null,
    "family": "Pythonidae",
    "genus": "Python",
    "inatId": 238252,
    "observationsThailand": 180,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Python_bivittatus",
    "wikipediaSummary": "The Burmese python (Python bivittatus) is one of the five largest species of snakes in the world (about the third-largest as measured either by length or weight). It is native to a large area of tropical South and Southeast Asia. Until 2009, it was considered a subspecies of Python molurus, but now is recognized as belonging to a distinct species.",
    "photo": {
      "url": "/snakes/238252.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Wayne Fidler, some rights reserved (CC BY-NC), uploaded by Wayne Fidler",
      "source": "https://www.inaturalist.org/photos/56087430"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-venustus",
    "sci": "Trimeresurus venustus",
    "en": "Beautiful Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30974,
    "observationsThailand": 176,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_venustus",
    "wikipediaSummary": "Trimeresurus kanburiensis is a species of pit viper found in only a few areas of Thailand. Highly venomous, it is an arboreal but heavily built species with a brown or tawny coloration. No subspecies are currently recognized.",
    "photo": {
      "url": "/snakes/30974.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Siriwat Dangsri, some rights reserved (CC BY-NC), uploaded by Siriwat Dangsri",
      "source": "https://www.inaturalist.org/photos/421873422"
    },
    "draft": true
  },
  {
    "id": "rhabdophis-nigrocinctus",
    "sci": "Rhabdophis nigrocinctus",
    "en": "Banded Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Rhabdophis",
    "inatId": 28838,
    "observationsThailand": 173,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rhabdophis_nigrocinctus",
    "wikipediaSummary": "Rhabdophis nigrocinctus, also known as the black-striped keelback, green Keelback, or banded keelback, is a keelback snake in the family Colubridae found in Myanmar, Thailand, Laos, Cambodia, Vietnam, and Yunnan (SW China).",
    "photo": {
      "url": "/snakes/28838.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Tommy, some rights reserved (CC BY-NC), uploaded by Tommy",
      "source": "https://www.inaturalist.org/photos/5677621"
    },
    "draft": true
  },
  {
    "id": "elaphe-taeniura",
    "sci": "Elaphe taeniura",
    "en": "Beauty Ratsnake",
    "th": null,
    "family": "Colubridae",
    "genus": "Elaphe",
    "inatId": 558884,
    "observationsThailand": 171,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Elaphe_taeniura",
    "wikipediaSummary": "The beauty rat snake (Orthriophis taeniurus), also called the beauty ratsnake, the beauty snake, or the cave racer, is a species of snake in the family Colubridae. The species is native to the eastern and southeastern regions of Asia. O. taeniurus is a long, thin, semi-arboreal species of snake with several recognized subspecies. This constrictor feeds on rodents, and though it is favored in some ",
    "photo": {
      "url": "/snakes/558884.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Liu Rui Wei, some rights reserved (CC BY-NC), uploaded by Liu Rui Wei",
      "source": "https://www.inaturalist.org/photos/345353806"
    },
    "draft": true
  },
  {
    "id": "fowlea-piscator",
    "sci": "Fowlea piscator",
    "en": "Chequered Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Fowlea",
    "inatId": 966799,
    "observationsThailand": 167,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Fowlea_piscator",
    "wikipediaSummary": "The checkered keelback (Fowlea piscator), also known commonly as the Asiatic water snake, is a common species of nonvenomous snake in the subfamily Natricinae of the family Colubridae. The species is endemic to Asia.",
    "photo": {
      "url": "/snakes/966799.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) K S Gopi Sundar, some rights reserved (CC BY-NC), uploaded by K S Gopi Sundar",
      "source": "https://www.inaturalist.org/photos/171413489"
    },
    "draft": true
  },
  {
    "id": "pareas-margaritophorus",
    "sci": "Pareas margaritophorus",
    "en": "White-spotted slug snake",
    "th": null,
    "family": "Pareidae",
    "genus": "Pareas",
    "inatId": 29138,
    "observationsThailand": 157,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Pareas_margaritophorus",
    "wikipediaSummary": "The mountain slug snake (Pareas margaritophorus), also known as the white-spotted slug snake, is a small, harmless species of snake that is rather common in South, South-East, and East Asia, and feeds on small invertebrates.",
    "photo": null,
    "draft": true
  },
  {
    "id": "indotyphlops-braminus",
    "sci": "Indotyphlops braminus",
    "en": "Brahminy Blindsnake",
    "th": null,
    "family": "Typhlopidae",
    "genus": "Indotyphlops",
    "inatId": 539844,
    "observationsThailand": 152,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Indotyphlops_braminus",
    "wikipediaSummary": "Indotyphlops braminus, commonly known as the brahminy blind snake and other names, is a nonvenomous blind snake species found mostly in Africa and Asia, but has been introduced in many other parts of the world. They are completely fossorial (i.e., burrowing) animals, with habits and appearance similar to earthworms, for which they are often mistaken, although close examination reveals tiny scales ",
    "photo": {
      "url": "/snakes/539844.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Toby, some rights reserved (CC BY-NC), uploaded by Toby",
      "source": "https://www.inaturalist.org/photos/504539229"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-purpureomaculatus",
    "sci": "Trimeresurus purpureomaculatus",
    "en": "Mangrove Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 98700,
    "observationsThailand": 149,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_purpureomaculatus",
    "wikipediaSummary": "Trimeresurus purpureomaculatus is a venomous pit viper species native to India, Bangladesh and Southeast Asia. Two subspecies are currently recognized, including the nominate subspecies described here.",
    "photo": {
      "url": "/snakes/98700.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) budak, some rights reserved (CC BY-NC), uploaded by budak",
      "source": "https://www.inaturalist.org/photos/7787354"
    },
    "draft": true
  },
  {
    "id": "lycodon-davisonii",
    "sci": "Lycodon davisonii",
    "en": "Blanford's Bridle Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 797712,
    "observationsThailand": 149,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_davisonii",
    "wikipediaSummary": "Blanford's bridle snake (Lycodon davisonii) is a species of harmless colubrid snake endemic to Asia. Blanford's bridle snake is so named because its slim body resembles the bridle used to control horses.",
    "photo": {
      "url": "/snakes/797712.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Thomas Calame, some rights reserved (CC BY-NC), uploaded by Thomas Calame",
      "source": "https://www.inaturalist.org/photos/5685393"
    },
    "draft": true
  },
  {
    "id": "enhydris-enhydris",
    "sci": "Enhydris enhydris",
    "en": "Rainbow Mud Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Enhydris",
    "inatId": 26770,
    "observationsThailand": 147,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Enhydris_enhydris",
    "wikipediaSummary": "The rainbow water snake (Enhydris enhydris) is a species of mildly venomous, rear-fanged, colubrid snake, endemic to Asia.",
    "photo": {
      "url": "/snakes/26770.jpeg",
      "license": "cc-by-nc-nd",
      "attribution": "(c) wildpokedex, some rights reserved (CC BY-NC-ND), uploaded by wildpokedex",
      "source": "https://www.inaturalist.org/photos/344755509"
    },
    "draft": true
  },
  {
    "id": "king-cobra",
    "sci": "Ophiophagus hannah",
    "en": "Northern King Cobra",
    "th": "งูจงอาง",
    "family": "Elapidae",
    "genus": "Ophiophagus",
    "inatId": 30472,
    "observationsThailand": 144,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ophiophagus_hannah",
    "wikipediaSummary": "The king cobra (Ophiophagus hannah), also known as the hamadryad, is a venomous snake species in the family Elapidae, endemic to forests from India through Southeast Asia. It is threatened by habitat destruction and has been listed as Vulnerable on the IUCN Red List since 2010. It is the world's longest venomous snake. Adult king cobras are 3.18 to 4 m (10.4 to 13.1 ft) long. The longest known ind",
    "photo": {
      "url": "/snakes/30472.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Daniel Liepack, some rights reserved (CC BY-NC), uploaded by Daniel Liepack",
      "source": "https://www.inaturalist.org/photos/307874083"
    },
    "draft": false,
    "danger": 5,
    "venom": "Neurotoxic",
    "size": "300–550 cm",
    "swatch": [
      "#3F4A2E",
      "#1F2517",
      "#C9B27A"
    ],
    "idCues": [
      "Narrow hood (not wide)",
      "Pale chevron bands on dark olive body",
      "Growl-like hiss"
    ],
    "habitat": "Forests, mangroves, bamboo near streams",
    "handle": "Do not approach. Back away slowly. Call snake catcher.",
    "firstAid": "Call 1669. Stay still. No tourniquet. Hospital fast — antivenom available."
  },
  {
    "id": "trimeresurus-hageni",
    "sci": "Trimeresurus hageni",
    "en": "Hagen’s Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30951,
    "observationsThailand": 135,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_hageni",
    "wikipediaSummary": "Trimeresurus hageni is a venomous pit viper species endemic to Southeast Asia. No subspecies are currently recognized.",
    "photo": {
      "url": "/snakes/30951.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Explore Herpetology, some rights reserved (CC BY-NC), uploaded by Explore Herpetology",
      "source": "https://www.inaturalist.org/photos/431871073"
    },
    "draft": true
  },
  {
    "id": "bungarus-fasciatus",
    "sci": "Bungarus fasciatus",
    "en": "Banded Krait",
    "th": null,
    "family": "Elapidae",
    "genus": "Bungarus",
    "inatId": 30448,
    "observationsThailand": 130,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Bungarus_fasciatus",
    "wikipediaSummary": "The banded krait (Bungarus fasciatus) is a species of elapid snake found on the Indian Subcontinent and in Southeast Asia. It is one of the largest kraits, with a maximum length up to 2.1 m (6 ft 11 in).",
    "photo": {
      "url": "/snakes/30448.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Robinp24, some rights reserved (CC BY-NC), uploaded by Robinp24",
      "source": "https://www.inaturalist.org/photos/635944683"
    },
    "draft": true
  },
  {
    "id": "pareas-berdmorei",
    "sci": "Pareas berdmorei",
    "en": null,
    "th": null,
    "family": "Pareidae",
    "genus": "Pareas",
    "inatId": 1367271,
    "observationsThailand": 126,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Pareas_berdmorei",
    "wikipediaSummary": "Pareas berdmorei, also known as the Mengla snail-eating snake or Berdmore's slug-eating snake, is a non-venomous snake native to Myanmar, China, Cambodia, Vietnam, Laos, and Thailand.",
    "photo": {
      "url": "/snakes/1367271.jpg",
      "license": "cc-by",
      "attribution": "(c) James Hunt, some rights reserved (CC BY), uploaded by James Hunt",
      "source": "https://www.inaturalist.org/photos/320100175"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-tenasserimensis",
    "sci": "Trimeresurus tenasserimensis",
    "en": "Tenasserim Green Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 1592011,
    "observationsThailand": 122,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1592011.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) mintkhaosok, some rights reserved (CC BY-NC), uploaded by mintkhaosok",
      "source": "https://www.inaturalist.org/photos/290476003"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-sabahi",
    "sci": "Trimeresurus sabahi",
    "en": "Sabah Bamboo Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30959,
    "observationsThailand": 108,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_sabahi",
    "wikipediaSummary": "Trimeresurus sabahi, commonly known as the Sabah bamboo pitviper, is a venomous pitviper species endemic to the island of Borneo.",
    "photo": {
      "url": "/snakes/30959.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) rharris70, some rights reserved (CC BY-NC), uploaded by rharris70",
      "source": "https://www.inaturalist.org/photos/6055461"
    },
    "draft": true
  },
  {
    "id": "lycodon-subannulatus",
    "sci": "Lycodon subannulatus",
    "en": "Malayan Bridal Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 797717,
    "observationsThailand": 106,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_subannulatus",
    "wikipediaSummary": "Lycodon subannulatus, the Malayan bridal snake or southern bridle snake, is a species of snake in the family Colubridae.",
    "photo": {
      "url": "/snakes/797717.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Gc Gan, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/33477570"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-phuketensis",
    "sci": "Trimeresurus phuketensis",
    "en": "Phuket Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 146511,
    "observationsThailand": 105,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_phuketensis",
    "wikipediaSummary": "Trimeresurus phuketensis (also known as the Phuket pit viper) is a species of pit viper found on Phuket Island in Thailand.",
    "photo": {
      "url": "/snakes/146511.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Lennart Schmid, some rights reserved (CC BY-NC), uploaded by Lennart Schmid",
      "source": "https://www.inaturalist.org/photos/253237469"
    },
    "draft": true
  },
  {
    "id": "rhabdophis-chrysargos",
    "sci": "Rhabdophis chrysargos",
    "en": "Specklebelly Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Rhabdophis",
    "inatId": 28845,
    "observationsThailand": 102,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rhabdophis_chrysargos",
    "wikipediaSummary": "The specklebelly keelback (Rhabdophis chrysargos) is a species of colubrid snake found in southeast Asia.",
    "photo": {
      "url": "/snakes/28845.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Farits Alhadi, some rights reserved (CC BY-NC), uploaded by Farits Alhadi",
      "source": "https://www.inaturalist.org/photos/5996853"
    },
    "draft": true
  },
  {
    "id": "xenochrophis-trianguligerus",
    "sci": "Xenochrophis trianguligerus",
    "en": "Triangle Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Xenochrophis",
    "inatId": 28055,
    "observationsThailand": 101,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Triangle_keelback",
    "wikipediaSummary": "The triangle keelback (Xenochrophis trianguligerus) is a species of snake found in Brunei Darussalam, Burma (Myanmar), Cambodia, India (Nicobar Islands; Arunachal Pradesh (Deban - Changlang district)), Indonesia (Nias, Mentawai, Sumatra, Riau Archipelago, Bangka, Billiton, Borneo, Java, Sulawesi=Celebes, Sangihe Archipelago, Ternate), Laos, Malaysia (Malaya and East Malaysia), Singapore, Thailand,",
    "photo": {
      "url": "/snakes/28055.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Wich’yanan (Jay) Limparungpatthanakij, some rights reserved (CC BY-NC), uploaded by Wich’yanan (Jay) Limparungpatthanakij",
      "source": "https://www.inaturalist.org/photos/85956479"
    },
    "draft": true
  },
  {
    "id": "lycodon-subcinctus",
    "sci": "Lycodon subcinctus",
    "en": "Malayan Banded Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 29546,
    "observationsThailand": 101,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_subcinctus",
    "wikipediaSummary": "Lycodon subcinctus, commonly known as the white-banded wolf snake or Malayan banded wolf snake, is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/29546.jpeg",
      "license": "cc0",
      "attribution": "no rights reserved, uploaded by Max Tibby",
      "source": "https://www.inaturalist.org/photos/431073884"
    },
    "draft": true
  },
  {
    "id": "boiga-siamensis",
    "sci": "Boiga siamensis",
    "en": "Eyed Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 27661,
    "observationsThailand": 96,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_siamensis",
    "wikipediaSummary": "The gray cat snake (Boiga siamensis), also known as eyed cat snake or Siamese cat snake is a species of catsnake found in northeastern India, Bangladesh, Myanmar, Cambodia, Thailand, Malaysia, and Vietnam.",
    "photo": {
      "url": "/snakes/27661.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Woraphot Bunkhwamdi, some rights reserved (CC BY-NC), uploaded by Woraphot Bunkhwamdi",
      "source": "https://www.inaturalist.org/photos/150387826"
    },
    "draft": true
  },
  {
    "id": "pareas-carinatus",
    "sci": "Pareas carinatus",
    "en": "Keeled Slug Snake",
    "th": null,
    "family": "Pareidae",
    "genus": "Pareas",
    "inatId": 29133,
    "observationsThailand": 95,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Pareas_carinatus",
    "wikipediaSummary": "The keeled slug-eating snake, Pareas carinatus, is a species of snake in the family Colubridae . It is relatively widespread in Southeast Asia, from southern China (Yunnan) to Burma and Indochina to the Malay Archipelago (Borneo, Java, Lombok, Sumatra, Bali). Two subspecies are recognized: P. c. carinatus and P. c. unicolor, the latter being confined to Cambodia.",
    "photo": {
      "url": "/snakes/29133.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Thomas Calame, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/140500"
    },
    "draft": true
  },
  {
    "id": "boiga-multomaculata",
    "sci": "Boiga multomaculata",
    "en": "Many-spotted Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 27678,
    "observationsThailand": 88,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_multomaculata",
    "wikipediaSummary": "Boiga multomaculata, also called the many-spotted cat snake, large-spotted cat snake and marbled cat-eyed snake, is a species of rear-fanged colubrid snakes of the genus Boiga.",
    "photo": {
      "url": "/snakes/27678.jpeg",
      "license": "cc-by",
      "attribution": "(c) Ian Dugdale, some rights reserved (CC BY), uploaded by Ian Dugdale",
      "source": "https://www.inaturalist.org/photos/86904174"
    },
    "draft": true
  },
  {
    "id": "calliophis-maculiceps",
    "sci": "Calliophis maculiceps",
    "en": "Speckled Coralsnake",
    "th": null,
    "family": "Elapidae",
    "genus": "Calliophis",
    "inatId": 30413,
    "observationsThailand": 85,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Calliophis_maculiceps",
    "wikipediaSummary": "Calliophis maculiceps, commonly known as the speckled coral snake or the small-spotted coral snake, is a species of venomous elapid snake endemic to Southeast Asia. Five subspecies are recognized, including the nominotypical subspecies.",
    "photo": {
      "url": "/snakes/30413.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) herpingvietnam, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/65158633"
    },
    "draft": true
  },
  {
    "id": "boiga-drapiezii",
    "sci": "Boiga drapiezii",
    "en": "White-spotted Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 95863,
    "observationsThailand": 81,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_drapiezii",
    "wikipediaSummary": "Boiga drapiezii, commonly known as the white-spotted cat snake, is a species of long and slender rear-fanged colubrid that is common throughout its range.",
    "photo": {
      "url": "/snakes/95863.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Farits Alhadi, some rights reserved (CC BY-NC), uploaded by Farits Alhadi",
      "source": "https://www.inaturalist.org/photos/5848776"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-subocularis",
    "sci": "Dendrelaphis subocularis",
    "en": "Mountain Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 26659,
    "observationsThailand": 76,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_subocularis",
    "wikipediaSummary": "Dendrelaphis subocularis, commonly known as the mountain bronzeback or Burmese bronzeback, is a species of snake in the family Colubridae from Southeast Asia.",
    "photo": {
      "url": "/snakes/26659.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Thomas Calame, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/139904"
    },
    "draft": true
  },
  {
    "id": "pareas-macularius",
    "sci": "Pareas macularius",
    "en": "Mountain Slug Snake",
    "th": null,
    "family": "Pareidae",
    "genus": "Pareas",
    "inatId": 1225654,
    "observationsThailand": 76,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Pareas_macularius",
    "wikipediaSummary": "Pareas macularius, the mountain slug snake, is a species of snake found in India, Bangladesh, Myanmar, Thailand, Laos, Vietnam, Malaysia, and China.",
    "photo": {
      "url": "/snakes/1225654.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/118903564"
    },
    "draft": true
  },
  {
    "id": "lycodon-fasciatus",
    "sci": "Lycodon fasciatus",
    "en": "Banded Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 29569,
    "observationsThailand": 75,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_fasciatus",
    "wikipediaSummary": "Lycodon fasciatus, commonly known as the banded wolf snake, is a species of colubrid snake.",
    "photo": {
      "url": "/snakes/29569.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) muangpaisuetrong, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/399084992"
    },
    "draft": true
  },
  {
    "id": "chrysopelea-paradisi",
    "sci": "Chrysopelea paradisi",
    "en": "Paradise Flying Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Chrysopelea",
    "inatId": 27214,
    "observationsThailand": 74,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Chrysopelea_paradisi",
    "wikipediaSummary": "Paradise tree snake or Paradise flying snake, Chrysopelea paradisi, is a species of snake found in southeastern Asia. It can, like all species of its genus Chrysopelea, glide by stretching the body into a flattened strip using its ribs. It is mostly found in moist forests and can cover a horizontal distance of about 100 metres in a glide from the top of a tree. Slow motion photography shows an und",
    "photo": {
      "url": "/snakes/27214.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Paul Donahue, some rights reserved (CC BY-NC), uploaded by Paul Donahue",
      "source": "https://www.inaturalist.org/photos/40471924"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-caudolineatus",
    "sci": "Dendrelaphis caudolineatus",
    "en": "Striped Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 26700,
    "observationsThailand": 73,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_caudolineatus",
    "wikipediaSummary": "Dendrelaphis caudolineatus is a common species of colubrid snake known commonly as the striped bronzeback or bronze tree snake. It is erroneously called 'garter snake' in the Philippines. It is not venomous and it is the most commonly sold snake as a pet. Though in captivity, they don't live as long as in the wild.",
    "photo": {
      "url": "/snakes/26700.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) fatahabib92, some rights reserved (CC BY-NC), uploaded by fatahabib92",
      "source": "https://www.inaturalist.org/photos/6503621"
    },
    "draft": true
  },
  {
    "id": "boiga-cynodon",
    "sci": "Boiga cynodon",
    "en": "Dog-toothed Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 27700,
    "observationsThailand": 71,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_cynodon",
    "wikipediaSummary": "Boiga cynodon, commonly known as the dog-toothed cat snake, is a nocturnal species of rear-fanged colubrid snake endemic to Asia.",
    "photo": {
      "url": "/snakes/27700.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Roy Kittrell, some rights reserved (CC BY-NC), uploaded by Roy Kittrell",
      "source": "https://www.inaturalist.org/photos/41803174"
    },
    "draft": true
  },
  {
    "id": "oreocryptophis-porphyraceus",
    "sci": "Oreocryptophis porphyraceus",
    "en": "Red Mountain Ratsnake",
    "th": null,
    "family": "Colubridae",
    "genus": "Oreocryptophis",
    "inatId": 30240,
    "observationsThailand": 71,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Oreocryptophis_porphyraceus",
    "wikipediaSummary": "Oreocryptophis porphyraceus is a rat snake species, commonly called the black-banded trinket snake, red bamboo snake or red mountain racer, found in mid to upper-level elevations of forested hills in southeastern Asia, ranging from evergreen tropical to dry seasonal forests depending on the subspecies and locality. It is the only member of the genus Oreocryptophis, but it was formerly placed in El",
    "photo": {
      "url": "/snakes/30240.jpg",
      "license": "cc-by-nc-sa",
      "attribution": "(c) Dash Huang, some rights reserved (CC BY-NC-SA)",
      "source": "https://www.inaturalist.org/photos/4483131"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-formosus",
    "sci": "Dendrelaphis formosus",
    "en": "Elegant Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 26696,
    "observationsThailand": 70,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_formosus",
    "wikipediaSummary": "Dendrelaphis formosus, also known as the elegant bronzeback, is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/26696.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Farits Alhadi, some rights reserved (CC BY-NC), uploaded by Farits Alhadi",
      "source": "https://www.inaturalist.org/photos/5848802"
    },
    "draft": true
  },
  {
    "id": "hypsiscopus-plumbeus",
    "sci": "Hypsiscopus plumbeus",
    "en": "Rice Paddy Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Hypsiscopus",
    "inatId": 539840,
    "observationsThailand": 70,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rice_paddy_snake",
    "wikipediaSummary": "The rice paddy snake (Hypsiscopus plumbea) is a species of mildly venomous, rear-fanged, colubrid snake endemic to South Asia.",
    "photo": {
      "url": "/snakes/539840.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Siriwat Dangsri, some rights reserved (CC BY-NC), uploaded by Siriwat Dangsri",
      "source": "https://www.inaturalist.org/photos/158565315"
    },
    "draft": true
  },
  {
    "id": "boiga-nigriceps",
    "sci": "Boiga nigriceps",
    "en": "Black-headed Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 27657,
    "observationsThailand": 67,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_nigriceps",
    "wikipediaSummary": "Boiga nigriceps (black-headed cat snake) is a species of colubrid snake from South-East Asia. They are large snakes; adults may attain a total length of 1.75 m (5 1⁄2 ft).",
    "photo": null,
    "draft": true
  },
  {
    "id": "trimeresurus-cardamomensis",
    "sci": "Trimeresurus cardamomensis",
    "en": "Cardamom Mountains Green Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30961,
    "observationsThailand": 67,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_cardamomensis",
    "wikipediaSummary": "Trimeresurus cardamomensis is a species of pit viper located in eastern Thailand and the Koh Kong Province in Cambodia. It is more commonly known as the Cardamom Mountains green pit viper.",
    "photo": {
      "url": "/snakes/30961.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Phakawat Kittikhunodom, some rights reserved (CC BY-NC), uploaded by Phakawat Kittikhunodom",
      "source": "https://www.inaturalist.org/photos/454588880"
    },
    "draft": true
  },
  {
    "id": "boiga-bengkuluensis",
    "sci": "Boiga bengkuluensis",
    "en": "Green-headed Cat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Boiga",
    "inatId": 95861,
    "observationsThailand": 67,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Boiga_bengkuluensis",
    "wikipediaSummary": "Boiga bengkuluensis is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/95861.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) bankv, some rights reserved (CC BY-NC), uploaded by bankv",
      "source": "https://www.inaturalist.org/photos/177898486"
    },
    "draft": true
  },
  {
    "id": "dryophiops-rubescens",
    "sci": "Dryophiops rubescens",
    "en": "Brown Whip Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Dryophiops",
    "inatId": 26798,
    "observationsThailand": 66,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dryophiops_rubescens",
    "wikipediaSummary": "Dryophiops rubescens, commonly known as the red whip snake, is a snake of the colubrid family.",
    "photo": {
      "url": "/snakes/26798.jpeg",
      "license": "cc-by",
      "attribution": "(c) anukma, some rights reserved (CC BY), uploaded by anukma",
      "source": "https://www.inaturalist.org/photos/12290436"
    },
    "draft": true
  },
  {
    "id": "plagiopholis-nuchalis",
    "sci": "Plagiopholis nuchalis",
    "en": "Assam Mountain Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Plagiopholis",
    "inatId": 109601,
    "observationsThailand": 63,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Plagiopholis_nuchalis",
    "wikipediaSummary": "Plagiopholis nuchalis, commonly known as the Assam mountain snake, is a species of colubrid snake. It is found in Yunnan (China), Myanmar, Thailand, Laos, possibly also in Assam region of India and in Vietnam. Specimens from Yunnan have been described as the subspecies Plagiopholis nuchalis kunmingensis.",
    "photo": {
      "url": "/snakes/109601.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Alexander Gregory Mason, some rights reserved (CC BY-NC), uploaded by Alexander Gregory Mason",
      "source": "https://www.inaturalist.org/photos/171063094"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-guoi",
    "sci": "Trimeresurus guoi",
    "en": "Guo's Green Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 1250148,
    "observationsThailand": 60,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1250148.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Keegan Tinsel, some rights reserved (CC BY-NC), uploaded by Keegan Tinsel",
      "source": "https://www.inaturalist.org/photos/464786265"
    },
    "draft": true
  },
  {
    "id": "ptyas-carinata",
    "sci": "Ptyas carinata",
    "en": "Keeled Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ptyas",
    "inatId": 28873,
    "observationsThailand": 59,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ptyas_carinata",
    "wikipediaSummary": "Commonly known as the keeled rat snake, Ptyas carinata is a species of colubrid snake. It is found in Indonesia, Myanmar, Malaysia, Thailand, Philippines, Cambodia, Vietnam and Singapore.",
    "photo": {
      "url": "/snakes/28873.jpg",
      "license": "cc-by-nc-sa",
      "attribution": "(c) viperskin, some rights reserved (CC BY-NC-SA)",
      "source": "https://www.inaturalist.org/photos/658293"
    },
    "draft": true
  },
  {
    "id": "gonyosoma-coeruleum",
    "sci": "Gonyosoma coeruleum",
    "en": "Blue-eyed Bush Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Gonyosoma",
    "inatId": 1304785,
    "observationsThailand": 58,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Gonyosoma_coeruleum",
    "wikipediaSummary": "Gonyosoma coeruleum is a species of non-venomous snake in the family Colubridae. The species is found in China, Vietnam, Thailand, Malaysia, and Myanmar.",
    "photo": {
      "url": "/snakes/1304785.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/169359083"
    },
    "draft": true
  },
  {
    "id": "pareas-yunnanensis",
    "sci": "Pareas yunnanensis",
    "en": null,
    "th": null,
    "family": "Pareidae",
    "genus": "Pareas",
    "inatId": 1474123,
    "observationsThailand": 58,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1474123.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Andrew Pierce, some rights reserved (CC BY-NC), uploaded by Andrew Pierce",
      "source": "https://www.inaturalist.org/photos/108700714"
    },
    "draft": true
  },
  {
    "id": "oligodon-purpurascens",
    "sci": "Oligodon purpurascens",
    "en": "Brown Kukri Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Oligodon",
    "inatId": 29229,
    "observationsThailand": 57,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Brown_kukri_snake",
    "wikipediaSummary": "The brown kukri snake (Oligodon purpurascens) is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/29229.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Bruce Teo, some rights reserved (CC BY-NC), uploaded by Bruce Teo",
      "source": "https://www.inaturalist.org/photos/162683622"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-ngansonensis",
    "sci": "Dendrelaphis ngansonensis",
    "en": "Vietnamese Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 26673,
    "observationsThailand": 55,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_ngansonensis",
    "wikipediaSummary": "Dendrelaphis ngansonensis, commonly known as either the Nganson bronzeback or Nganson bronzeback tree snake, is a species of snake in the family Colubridae, sound in Southeast Asia.",
    "photo": {
      "url": "/snakes/26673.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) mark_spence, some rights reserved (CC BY-NC), uploaded by mark_spence",
      "source": "https://www.inaturalist.org/photos/72894100"
    },
    "draft": true
  },
  {
    "id": "aplopeltura-boa",
    "sci": "Aplopeltura boa",
    "en": "Blunthead Slug Snake",
    "th": null,
    "family": "Pareidae",
    "genus": "Aplopeltura",
    "inatId": 28442,
    "observationsThailand": 55,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Aplopeltura_boa",
    "wikipediaSummary": "Aplopeltura is a genus of snakes of the family Pareidae. It contains a single species, Aplopeltura boa, the blunthead slug snake or blunt-headed slug-eating snake. It is a small, non-venomous snake. The species can be found in southern Thailand, Malaysia, Indonesia, Brunei and the Philippines.",
    "photo": {
      "url": "/snakes/28442.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) vteo2, some rights reserved (CC BY-NC), uploaded by vteo2",
      "source": "https://www.inaturalist.org/photos/29801243"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-cyanochloris",
    "sci": "Dendrelaphis cyanochloris",
    "en": "Blue Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 26694,
    "observationsThailand": 53,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_cyanochloris",
    "wikipediaSummary": "Dendrelaphis cyanochloris, commonly known as Wall's Bronzeback, is a species of snake found in Southeast Asia.",
    "photo": {
      "url": "/snakes/26694.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Li Jianong, some rights reserved (CC BY-NC), uploaded by Li Jianong",
      "source": "https://www.inaturalist.org/photos/263290752"
    },
    "draft": true
  },
  {
    "id": "ptyas-fusca",
    "sci": "Ptyas fusca",
    "en": "Brown Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ptyas",
    "inatId": 28869,
    "observationsThailand": 52,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ptyas_fusca",
    "wikipediaSummary": "Ptyas fusca, commonly known as the White-bellied Rat Snake or Brown Rat Snake, is a species of colubrid snake. It is found in Indonesia, Brunei, Malaysia, Thailand and Singapore.",
    "photo": {
      "url": "/snakes/28869.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) John Sullivan, some rights reserved (CC BY-NC), uploaded by John Sullivan",
      "source": "https://www.inaturalist.org/photos/6294380"
    },
    "draft": true
  },
  {
    "id": "oligodon-mouhoti",
    "sci": "Oligodon mouhoti",
    "en": "Cambodian Kukri Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Oligodon",
    "inatId": 107476,
    "observationsThailand": 52,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Oligodon_mouhoti",
    "wikipediaSummary": "Oligodon mouhoti, also known as the Cambodian kukri snake or Mouhot's kukri snake, is a species of snake of the family Colubridae. It was named for French naturalist Henri Mouhot.",
    "photo": {
      "url": "/snakes/107476.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Rueangrit Promdam, some rights reserved (CC BY-NC), uploaded by Rueangrit Promdam",
      "source": "https://www.inaturalist.org/photos/12005689"
    },
    "draft": true
  },
  {
    "id": "calliophis-bivirgatus",
    "sci": "Calliophis bivirgatus",
    "en": "Blue Malaysian Coralsnake",
    "th": null,
    "family": "Elapidae",
    "genus": "Calliophis",
    "inatId": 558849,
    "observationsThailand": 52,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Calliophis_bivirgata",
    "wikipediaSummary": "Calliophis bivirgata (syn. C. bivirgatus) is a species of snake in the family Elapidae known commonly as the blue coral snake or blue Malayan coral snake. It is native to Southeast Asia.",
    "photo": {
      "url": "/snakes/558849.jpg",
      "license": "cc-by",
      "attribution": "(c) dhfischer, some rights reserved (CC BY), uploaded by dhfischer",
      "source": "https://www.inaturalist.org/photos/103225556"
    },
    "draft": true
  },
  {
    "id": "erpeton-tentaculatum",
    "sci": "Erpeton tentaculatum",
    "en": "Tentacled Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Erpeton",
    "inatId": 30164,
    "observationsThailand": 49,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Erpeton_tentaculatum",
    "wikipediaSummary": "The tentacled snake or tentacle snake (Erpeton tentaculatum), is a rear-fanged aquatic snake native to South-East Asia. It is the only species of its genus, Erpeton, and the two tentacles on its snout are a unique feature among snakes. The method it uses to catch fish has recently been a subject of research.",
    "photo": {
      "url": "/snakes/30164.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Jeremy P., some rights reserved (CC BY-NC), uploaded by Jeremy P.",
      "source": "https://www.inaturalist.org/photos/335960148"
    },
    "draft": true
  },
  {
    "id": "homalopsis-buccata",
    "sci": "Homalopsis buccata",
    "en": "Puff-faced Water Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Homalopsis",
    "inatId": 29910,
    "observationsThailand": 48,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Homalopsis_buccata",
    "wikipediaSummary": "Puff-faced Water Snake or Masked Water Snake (Homalopsis buccata) is a species of water snake found in tropical areas of South and Southeast Asia.",
    "photo": {
      "url": "/snakes/29910.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Auzan Sukaton, some rights reserved (CC BY-NC), uploaded by Auzan Sukaton",
      "source": "https://www.inaturalist.org/photos/57641069"
    },
    "draft": true
  },
  {
    "id": "bungarus-flaviceps",
    "sci": "Bungarus flaviceps",
    "en": "Red-headed Krait",
    "th": null,
    "family": "Elapidae",
    "genus": "Bungarus",
    "inatId": 70012,
    "observationsThailand": 48,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Red-headed_krait",
    "wikipediaSummary": "The red-headed krait (Bungarus flaviceps), is a large venomous elapid snake with dramatic coloration. The red-headed krait can grow to a length of up to 7 feet (2.1 m). It lives in lowland rain forest, including those on islands, but it is considered uncommon. It feeds primarily on specific snakes, probably semiaquatic and fossorial snakes. In Southeast Asia, the red-headed krait occurs in Malaysi",
    "photo": {
      "url": "/snakes/70012.jpg",
      "license": "cc-by-sa",
      "attribution": "(c) Henning Larsen, some rights reserved (CC BY-SA)",
      "source": "https://www.inaturalist.org/photos/11823078"
    },
    "draft": true
  },
  {
    "id": "naja-fuxi",
    "sci": "Naja fuxi",
    "en": "Brown Banded Cobra",
    "th": null,
    "family": "Elapidae",
    "genus": "Naja",
    "inatId": 1438742,
    "observationsThailand": 47,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Brown_banded_cobra",
    "wikipediaSummary": "The brown banded cobra (Naja fuxi) is a species of venomous cobra, endemic to Southeast Asia. It was considered to be a part of Naja kaouthia until genetic studies conducted in 2022 rendered it a separate species.",
    "photo": {
      "url": "/snakes/1438742.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) guliwu_island, some rights reserved (CC BY-NC), uploaded by guliwu_island",
      "source": "https://www.inaturalist.org/photos/122906929"
    },
    "draft": true
  },
  {
    "id": "ahaetulla-mycterizans",
    "sci": "Ahaetulla mycterizans",
    "en": "Malayan Whipsnake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ahaetulla",
    "inatId": 93578,
    "observationsThailand": 46,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ahaetulla_mycterizans",
    "wikipediaSummary": "Ahaetulla mycterizans, the Malayan green whipsnake or Malayan vine snake, is a slender arboreal snake found in Western Peninsular Malaysia, Java and Sumatra of Indonesia, Singapore, Thailand and possibly Laos up to elevation of 350 m.",
    "photo": {
      "url": "/snakes/93578.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) venus5026, some rights reserved (CC BY-NC), uploaded by venus5026",
      "source": "https://www.inaturalist.org/photos/53946776"
    },
    "draft": true
  },
  {
    "id": "coelognathus-flavolineatus",
    "sci": "Coelognathus flavolineatus",
    "en": "Black Copper Rat Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Coelognathus",
    "inatId": 30268,
    "observationsThailand": 45,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Coelognathus_flavolineatus",
    "wikipediaSummary": "Coelognathus flavolineatus, the black copper rat snake or yellow striped snake, is a species of Colubrid snake found in Southeast Asia. This species was previously recognized in the genus Elaphe.",
    "photo": {
      "url": "/snakes/30268.jpg",
      "license": "cc-by",
      "attribution": "(c) dhfischer, some rights reserved (CC BY), uploaded by dhfischer",
      "source": "https://www.inaturalist.org/photos/103394963"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-kanburiensis",
    "sci": "Trimeresurus kanburiensis",
    "en": "Kanburi Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30965,
    "observationsThailand": 45,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_kanburiensis",
    "wikipediaSummary": "Trimeresurus kanburiensis is a species of pit viper found in only a few areas of Thailand. Highly venomous, it is an arboreal but heavily built species with a brown or tawny coloration. No subspecies are currently recognized.",
    "photo": {
      "url": "/snakes/30965.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) muangpaisuetrong, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/587642481"
    },
    "draft": true
  },
  {
    "id": "ophiophagus-bungarus",
    "sci": "Ophiophagus bungarus",
    "en": "Sunda King Cobra",
    "th": null,
    "family": "Elapidae",
    "genus": "Ophiophagus",
    "inatId": 1629671,
    "observationsThailand": 45,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ophiophagus_bungarus",
    "wikipediaSummary": "Ophiophagus bungarus, the Sunda king cobra, is a species of king cobra that inhabits areas south of the Kra Isthmus or land bridge joining the Malay Peninsula with the rest of southeast Asia or Indochina. The countries it is found in include southern Thailand (deep south), western Malaysia, Singapore and offshore islands, Sumatra, Borneo, Java, Bali, and some of the islands of the southern Philipp",
    "photo": null,
    "draft": true
  },
  {
    "id": "ovophis-monticola",
    "sci": "Ovophis monticola",
    "en": "Chinese Mountain Pit Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Ovophis",
    "inatId": 31024,
    "observationsThailand": 44,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ovophis_monticola",
    "wikipediaSummary": "Ovophis monticola is a venomous pitviper species found in Asia. Currently, five subspecies are recognized, including the nominate subspecies described here. Recent taxonomic work suggests that most of these should be considered as separate species. IUCN has already evaluated O. m. makazayazaya as Ovophis makazayazaya.",
    "photo": {
      "url": "/snakes/31024.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Thomas Calame, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/141804"
    },
    "draft": true
  },
  {
    "id": "python-regius",
    "sci": "Python regius",
    "en": "Ball Python",
    "th": null,
    "family": "Pythonidae",
    "genus": "Python",
    "inatId": 32158,
    "observationsThailand": 42,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Python_regius",
    "wikipediaSummary": "The ball python (Python regius), also known as the royal python, is a python species found in sub-Saharan Africa. Like all other pythons, it is a non-venomous constrictor. This is the smallest of the African pythons and is popular in the pet trade, largely due to its small size and typically docile temperament. No subspecies are currently recognized. The name \"ball python\" refers to the animal's t",
    "photo": {
      "url": "/snakes/32158.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) cristalvirella, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/127328258"
    },
    "draft": true
  },
  {
    "id": "lycodon-effraenis",
    "sci": "Lycodon effraenis",
    "en": "Scarce Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 29570,
    "observationsThailand": 41,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_effraenis",
    "wikipediaSummary": "The brown wolf snake (Lycodon effraenis) is a species of snake in the family colubridae. It is found in Malaysia, Brunei, Indonesia, and Thailand.",
    "photo": null,
    "draft": true
  },
  {
    "id": "sibynophis-collaris",
    "sci": "Sibynophis collaris",
    "en": "Collared Black-headed Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Sibynophis",
    "inatId": 28671,
    "observationsThailand": 40,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Sibynophis_collaris",
    "wikipediaSummary": "Sibynophis collaris, commonly known as the common many-toothed snake or the collared black-headed snake, is a species of colubrid snake endemic to South Asia.",
    "photo": {
      "url": "/snakes/28671.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/182542505"
    },
    "draft": true
  },
  {
    "id": "pseudoxenodon-macrops",
    "sci": "Pseudoxenodon macrops",
    "en": "Big-eyed Bamboo Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Pseudoxenodon",
    "inatId": 28902,
    "observationsThailand": 38,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Pseudoxenodon_macrops",
    "wikipediaSummary": "Pseudoxenodon macrops, commonly known as the large-eyed bamboo snake or the Chinese false cobra, is a species of venomous rear-fanged snake endemic to Asia.",
    "photo": {
      "url": "/snakes/28902.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Leonid A. Neymark, some rights reserved (CC BY-NC), uploaded by Leonid A. Neymark",
      "source": "https://www.inaturalist.org/photos/48244865"
    },
    "draft": true
  },
  {
    "id": "python-brongersmai",
    "sci": "Python brongersmai",
    "en": "Malaysian Blood Python",
    "th": null,
    "family": "Pythonidae",
    "genus": "Python",
    "inatId": 32162,
    "observationsThailand": 36,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Python_brongersmai",
    "wikipediaSummary": "Python brongersmai, commonly known as Brongersma's short-tailed python, the blood python, or the red short-tailed python, is a species of python, a nonvenomous snake endemic to the Malay Peninsula.",
    "photo": {
      "url": "/snakes/32162.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Siriwat Dangsri, some rights reserved (CC BY-NC), uploaded by Siriwat Dangsri",
      "source": "https://www.inaturalist.org/photos/91757434"
    },
    "draft": true
  },
  {
    "id": "calamaria-pavimentata",
    "sci": "Calamaria pavimentata",
    "en": "Collared Reed Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Calamaria",
    "inatId": 27433,
    "observationsThailand": 35,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Calamaria_pavimentata",
    "wikipediaSummary": "The collared reed snake (Calamaria pavimentata) is a species of colubrid snake found in Asia. In Japan, it is also called Miyara's collared snake.",
    "photo": null,
    "draft": true
  },
  {
    "id": "trimeresurus-gumprechti",
    "sci": "Trimeresurus gumprechti",
    "en": "Gumprecht's Green Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30976,
    "observationsThailand": 34,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_gumprechti",
    "wikipediaSummary": "Trimeresurus gumprechti (Gumprecht's green pitviper) is a species of venomous pitviper endemic to Asia.",
    "photo": {
      "url": "/snakes/30976.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/169359511"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-kuiburi",
    "sci": "Trimeresurus kuiburi",
    "en": "Kui Buri Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 1250279,
    "observationsThailand": 34,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1250279.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) vihtorimallat, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/484777780"
    },
    "draft": true
  },
  {
    "id": "hebius-khasiensis",
    "sci": "Hebius khasiensis",
    "en": "Khasi Hills Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Hebius",
    "inatId": 539784,
    "observationsThailand": 32,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Hebius_khasiensis",
    "wikipediaSummary": "Hebius khasiense, commonly known as the Khasi Hills keelback or Khasi keelback, is a species of colubrid snake endemic to southeastern Asia.",
    "photo": {
      "url": "/snakes/539784.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/145180126"
    },
    "draft": true
  },
  {
    "id": "oligodon-barroni",
    "sci": "Oligodon barroni",
    "en": "Barron's Kukri Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Oligodon",
    "inatId": 29272,
    "observationsThailand": 31,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Oligodon_barroni",
    "wikipediaSummary": "Oligodon barroni is a species of snake in the family Colubridae. The species is endemic to Southeast Asia.",
    "photo": null,
    "draft": true
  },
  {
    "id": "naja-sumatrana",
    "sci": "Naja sumatrana",
    "en": "Equatorial Spitting Cobra",
    "th": null,
    "family": "Elapidae",
    "genus": "Naja",
    "inatId": 106451,
    "observationsThailand": 31,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Naja_sumatrana",
    "wikipediaSummary": "Equatorial spitting cobra (Naja sumatrana) also called the black spitting cobra, Malayan spitting cobra, golden spitting cobra, or Sumatran spitting cobra, is a species of spitting cobra found in Southeast Asia.",
    "photo": {
      "url": "/snakes/106451.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Eno Sumarno, some rights reserved (CC BY-NC), uploaded by Eno Sumarno",
      "source": "https://www.inaturalist.org/photos/4654697"
    },
    "draft": true
  },
  {
    "id": "fordonia-leucobalia",
    "sci": "Fordonia leucobalia",
    "en": "White-bellied Mangrove Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Fordonia",
    "inatId": 30089,
    "observationsThailand": 30,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Fordonia_leucobalia",
    "wikipediaSummary": "Fordonia leucobalia is an aquatic snake known by the common names crab-eating water snake and white-bellied mangrove snake. It is a common resident of mangrove swamps and tropical tidal wetlands from coast of Southeast Asia to Indonesia and the coasts of Northern Australia.",
    "photo": {
      "url": "/snakes/30089.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Alfonsus Toribio Eko Saputro, some rights reserved (CC BY-NC), uploaded by Alfonsus Toribio Eko Saputro",
      "source": "https://www.inaturalist.org/photos/106175410"
    },
    "draft": true
  },
  {
    "id": "rhabdophis-helleri",
    "sci": "Rhabdophis helleri",
    "en": "Heller's Red-necked Keelback",
    "th": null,
    "family": "Colubridae",
    "genus": "Rhabdophis",
    "inatId": 1337912,
    "observationsThailand": 30,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rhabdophis_helleri",
    "wikipediaSummary": "Rhabdophis helleri, also known commonly as Heller’s red-necked keelback, is a venomous species of keelback snake in the subfamily Natricinae of the family Colubridae. The species is native to South Asia.",
    "photo": {
      "url": "/snakes/1337912.jpg",
      "license": "cc-by",
      "attribution": "(c) Lawrence Hylton, some rights reserved (CC BY), uploaded by Lawrence Hylton",
      "source": "https://www.inaturalist.org/photos/170422986"
    },
    "draft": true
  },
  {
    "id": "lycodon-neomaculatus",
    "sci": "Lycodon neomaculatus",
    "en": "Indochinese Banded Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 1623087,
    "observationsThailand": 30,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_neomaculatus",
    "wikipediaSummary": "Lycodon neomaculatus, the Indochinese banded wolfsnake, is a snake found in Cambodia, Laos, Myanmar, Thailand and Vietnam.",
    "photo": {
      "url": "/snakes/1623087.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/461145134"
    },
    "draft": true
  },
  {
    "id": "calliophis-intestinalis",
    "sci": "Calliophis intestinalis",
    "en": "Banded Malaysian Coralsnake",
    "th": null,
    "family": "Elapidae",
    "genus": "Calliophis",
    "inatId": 30430,
    "observationsThailand": 28,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Calliophis_intestinalis",
    "wikipediaSummary": "Calliophis intestinalis, commonly known as the banded Malaysian coral snake, is a species of venomous elapid snake endemic to Southeast Asia.",
    "photo": {
      "url": "/snakes/30430.jpg",
      "license": "cc-by-nc-sa",
      "attribution": "(c) Alex Figueroa, some rights reserved (CC BY-NC-SA)",
      "source": "https://www.inaturalist.org/photos/1461071"
    },
    "draft": true
  },
  {
    "id": "daboia-siamensis",
    "sci": "Daboia siamensis",
    "en": "Siamese Russell's Viper",
    "th": null,
    "family": "Viperidae",
    "genus": "Daboia",
    "inatId": 145768,
    "observationsThailand": 28,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Daboia_siamensis",
    "wikipediaSummary": "Daboia siamensis is a venomous viper species that is endemic to parts of Southeast Asia, southern China and Taiwan. It was formerly considered to be a subspecies of Daboia russelii (as Daboia russelli siamensis), but was elevated to species status in 2007.",
    "photo": {
      "url": "/snakes/145768.jpg",
      "license": "cc-by-sa",
      "attribution": "(c) Manoj Karingamadathil, some rights reserved (CC BY-SA)",
      "source": "https://www.inaturalist.org/photos/465909283"
    },
    "draft": true
  },
  {
    "id": "ahaetulla-fasciolata",
    "sci": "Ahaetulla fasciolata",
    "en": "Speckle-headed Whipsnake",
    "th": null,
    "family": "Colubridae",
    "genus": "Ahaetulla",
    "inatId": 30194,
    "observationsThailand": 26,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ahaetulla_fasciolata",
    "wikipediaSummary": "The speckle-headed whipsnake (Ahaetulla fasciolata) is a species of snake of the family Colubridae.",
    "photo": {
      "url": "/snakes/30194.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) phangnga_base, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/1839001"
    },
    "draft": true
  },
  {
    "id": "enhydris-subtaeniata",
    "sci": "Enhydris subtaeniata",
    "en": "Mekong Mud Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Enhydris",
    "inatId": 99985,
    "observationsThailand": 26,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/99985.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Jeff LeClere, some rights reserved (CC BY-NC), uploaded by Jeff LeClere",
      "source": "https://www.inaturalist.org/photos/89211025"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-haasi",
    "sci": "Dendrelaphis haasi",
    "en": "Haas's Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 99186,
    "observationsThailand": 25,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_haasi",
    "wikipediaSummary": "Dendrelaphis haasi, also known commonly as Haas' bronzeback, Haas's bronzeback, Haas's bronzeback snake, and Haas's bronzeback tree snake, is a species of snake in the family Colubridae. The species is native to Southeast Asia.",
    "photo": {
      "url": "/snakes/99186.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) budak, some rights reserved (CC BY-NC), uploaded by budak",
      "source": "https://www.inaturalist.org/photos/18659961"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-striatus",
    "sci": "Dendrelaphis striatus",
    "en": "Banded Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 99190,
    "observationsThailand": 25,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_striatus",
    "wikipediaSummary": "Dendrelaphis striatus, commonly known as the banded bronzeback or striated bronzeback treesnake, is a species of snake of the family Colubridae found in Southeast Asia.",
    "photo": {
      "url": "/snakes/99190.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) rangkuty16, some rights reserved (CC BY-NC), uploaded by rangkuty16",
      "source": "https://www.inaturalist.org/photos/7474806"
    },
    "draft": true
  },
  {
    "id": "argyrophis-muelleri",
    "sci": "Argyrophis muelleri",
    "en": "Müller's Blind Snake",
    "th": null,
    "family": "Typhlopidae",
    "genus": "Argyrophis",
    "inatId": 539372,
    "observationsThailand": 25,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/539372.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) herpingvietnam, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/70551558"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-ciliaris",
    "sci": "Trimeresurus ciliaris",
    "en": "Limestone Eyelash Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 1545842,
    "observationsThailand": 25,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1545842.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/321299030"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-yunnanensis",
    "sci": "Trimeresurus yunnanensis",
    "en": "Yunnan Bamboo Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 30948,
    "observationsThailand": 24,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trimeresurus_yunnanensis",
    "wikipediaSummary": "Trimeresurus stejnegeri yunnanensis is a venomous pitviper subspecies endemic to China.",
    "photo": {
      "url": "/snakes/30948.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) guanchayuan, some rights reserved (CC BY-NC)",
      "source": "https://www.inaturalist.org/photos/51194722"
    },
    "draft": true
  },
  {
    "id": "lycodon-chapaensis",
    "sci": "Lycodon chapaensis",
    "en": "Namdong Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 1250064,
    "observationsThailand": 24,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_chapaensis",
    "wikipediaSummary": "Lycodon chapaensis, the Namdong wolf snake, is a species of snake found in Vietnam and China.",
    "photo": {
      "url": "/snakes/1250064.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) 通通, some rights reserved (CC BY-NC), uploaded by 通通",
      "source": "https://www.inaturalist.org/photos/185859716"
    },
    "draft": true
  },
  {
    "id": "pseudoindotyphlops-porrectus",
    "sci": "Pseudoindotyphlops porrectus",
    "en": "Slender Worm Snake",
    "th": null,
    "family": "Typhlopidae",
    "genus": "Pseudoindotyphlops",
    "inatId": 1545776,
    "observationsThailand": 24,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1545776.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Jonathan Hakim, some rights reserved (CC BY-NC), uploaded by Jonathan Hakim",
      "source": "https://www.inaturalist.org/photos/112964644"
    },
    "draft": true
  },
  {
    "id": "acrochordus-granulatus",
    "sci": "Acrochordus granulatus",
    "en": "Little File Snake",
    "th": null,
    "family": "Acrochordidae",
    "genus": "Acrochordus",
    "inatId": 26182,
    "observationsThailand": 22,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Acrochordus_granulatus",
    "wikipediaSummary": "Acrochordus granulatus is a snake species found from India through Southeast Asia to the Solomon Islands. It is completely aquatic and almost helpless on land. No subspecies are currently recognized.",
    "photo": {
      "url": "/snakes/26182.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) uwkwaj, some rights reserved (CC BY-NC), uploaded by uwkwaj",
      "source": "https://www.inaturalist.org/photos/329993515"
    },
    "draft": true
  },
  {
    "id": "homalopsis-nigroventralis",
    "sci": "Homalopsis nigroventralis",
    "en": "Deuve's Water Snake",
    "th": null,
    "family": "Homalopsidae",
    "genus": "Homalopsis",
    "inatId": 29912,
    "observationsThailand": 22,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/29912.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Jeff LeClere, some rights reserved (CC BY-NC), uploaded by Jeff LeClere",
      "source": "https://www.inaturalist.org/photos/89211235"
    },
    "draft": true
  },
  {
    "id": "lycodon-albofuscus",
    "sci": "Lycodon albofuscus",
    "en": "Dark Wolf Snake",
    "th": null,
    "family": "Colubridae",
    "genus": "Lycodon",
    "inatId": 797710,
    "observationsThailand": 22,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lycodon_albofuscus",
    "wikipediaSummary": "The dark wolf snake (Lycodon albofuscus) is species of snake in the family colubridae. It is found in Asia.",
    "photo": {
      "url": "/snakes/797710.jpeg",
      "license": "cc-by-nc-nd",
      "attribution": "(c) wildpokedex, some rights reserved (CC BY-NC-ND), uploaded by wildpokedex",
      "source": "https://www.inaturalist.org/photos/455846174"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-vogeli",
    "sci": "Dendrelaphis vogeli",
    "en": "Vogel's Bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 1119964,
    "observationsThailand": 22,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_vogeli",
    "wikipediaSummary": "Dendrelaphis vogeli, Vogel's bronzeback, is a species of snake in the family Colubridae. The species is found in China and Thailand.",
    "photo": {
      "url": "/snakes/1119964.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/138958078"
    },
    "draft": true
  },
  {
    "id": "trimeresurus-kraensis",
    "sci": "Trimeresurus kraensis",
    "en": "Kra Isthmus Pitviper",
    "th": null,
    "family": "Viperidae",
    "genus": "Trimeresurus",
    "inatId": 1592008,
    "observationsThailand": 22,
    "wikipediaUrl": null,
    "wikipediaSummary": null,
    "photo": {
      "url": "/snakes/1592008.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Nick Volpe, some rights reserved (CC BY-NC), uploaded by Nick Volpe",
      "source": "https://www.inaturalist.org/photos/402711647"
    },
    "draft": true
  },
  {
    "id": "dendrelaphis-nigroserratus",
    "sci": "Dendrelaphis nigroserratus",
    "en": "sawtooth-necked bronzeback",
    "th": null,
    "family": "Colubridae",
    "genus": "Dendrelaphis",
    "inatId": 146085,
    "observationsThailand": 21,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dendrelaphis_nigroserratus",
    "wikipediaSummary": "Dendrelaphis nigroserratus (common name: sawtooth-necked bronzeback) is a species of snakes belonging to the bronzebacks (Dendrelaphis). It is found only in western and southwestern Thailand and the adjacent southeastern Myanmar. A specimen has been preserved in the British Natural History Museum, London since the early 20th century. Due to its resemblance to Wall's Bronzeback, the scientific name",
    "photo": {
      "url": "/snakes/146085.jpg",
      "license": "cc-by-nc",
      "attribution": "(c) Tomáš Hovorka, some rights reserved (CC BY-NC), uploaded by Tomáš Hovorka",
      "source": "https://www.inaturalist.org/photos/170556832"
    },
    "draft": true
  },
  {
    "id": "sinomicrurus-macclellandi",
    "sci": "Sinomicrurus macclellandi",
    "en": "MacClelland’s Coral Snake",
    "th": null,
    "family": "Elapidae",
    "genus": "Sinomicrurus",
    "inatId": 30419,
    "observationsThailand": 20,
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Sinomicrurus_macclellandi",
    "wikipediaSummary": "Sinomicrurus macclellandi, commonly known as MacClelland's coral snake, is a species of venomous elapid snake endemic to southern and eastern Asia.",
    "photo": {
      "url": "/snakes/30419.jpeg",
      "license": "cc-by-nc",
      "attribution": "(c) Parinya Pawangkhanant, some rights reserved (CC BY-NC), uploaded by Parinya Pawangkhanant",
      "source": "https://www.inaturalist.org/photos/181287848"
    },
    "draft": true
  }
];
